<?php

namespace AYM\ApiBundle\Entity;

/**
 * AbstractTaxonomyTermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractTaxonomyTermRepository extends BaseEntityRepository
{
}
