<?php

namespace AYM\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BaseEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class BaseEntityRepository extends EntityRepository
{
}
